### PR TITLE
Add How-It-Works section for landing page

### PR DESCRIPTION
**Pull request by akshkin**
**Description**
This PR adds a "How it Works" section for the landing page which is fully responsive as per the figma file by Atom.
Used an array to store the different feature text and images for the section.

**Changes made** 

- to `tailwind.config.cjs` file:
  - Defined custom font - 'Poppins'
  - Configured a custom breakpoint for small screens
  
- to `src` directory:
  - Added a components folder to add the HowItWorks component
  - Added an `index.js` in the `components` folder file to export the component.

Please review and let me know if any changes are needed. Thank you!

### CODE REVIEW

**Comment by hamdi4-beep** [comment]
This PR is clear!

**Review by hamdi4-beep — APPROVED** [review]
I've looked into the file changes! Looks clean!

**Comment by akshkin** [comment]
Thank you!

**Review by hamdi4-beep — COMMENTED** [review]
Hey, @akshkin I think you forgot to stage the HowItWorks component. Could you please look into it?

**Comment by akshkin** [comment]
@hamdi4-beep I'll look into it!

**Comment by akshkin** [comment]
@hamdi4-beep I've pulled the changes and then added HowItWorks component in the Main component.

**Pull request merged**
